stages:
  - node-build
  - test
  - docker-build

node-build:
 image: node:10.23.1-alpine
 stage: node-build
 script:
   - npm run get-dependencies
   - npm run client:build

test:
  image: node:10.23.1-alpine
  stage: test
  script:
    - cd ./client &&npm run test

cache:
 paths:
   - node_modules/

docker-build:
 image: docker:latest
 stage: docker-build
 services:
   - docker:dind
 script:
#todo test
   - ls
   - rm -rf client/
   - docker build . --tag app
#todo test
   - docker images