#todo add comments
stages:
  - node-build
  - test
  - docker-build-and-push

node-build:
 image: node:10.23.1-alpine
 stage: node-build
 script:
   - npm run get-dependencies --prefix app
   - npm run client:build --prefix app
 cache:
   key: node-cache
   paths:
     - app/node_modules/
     - app/client/node_modules/
 artifacts:
   paths:
     - app/build/
   expire_in: 5 min

test:
  image: node:10.23.1-alpine
  stage: test
  cache:
    key: node-cache
    paths:
      - app/client/node_modules/
  script:
    - npm run test --prefix app/client

docker-build-and-push:
 image: docker:latest
 stage: docker-build-and-push
 cache:
   key: node-cache
   paths:
     - app/node_modules/
 services:
   - docker:dind
 script:
   - ls app/node_modules
   - rm -rf app/client/
   - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
   - docker build . --tag $DOCKER_USER/app:$CI_PIPELINE_IID
   - docker push $DOCKER_USER/app:$CI_PIPELINE_IID