---
- name: copy monitoring files
  copy:
    src: monitoring
    dest: /home

- name: start prometheus and grafana
  shell: cd /home/monitoring &&docker-compose --log-level ERROR down &&docker-compose --log-level ERROR up -d