---
- name: copy docker-compose.yml
  copy:
    src: app
    dest: /home

- name: up app container
  shell: cd /home/app &&docker-compose --log-level ERROR down &&docker-compose --env vars.env --log-level ERROR up -d